version: "3.9"
services:
  apptest:
    container_name: "app-test"
    build: ./tracking-service
    command: npm run test
    networks:
      - tracking-network
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: "tracking-db"
    image: mongo
    networks:
      - tracking-network
    ports:
      - 27017:27017
  mongo-seed:
    container_name: "mongo-seed"
    build: ./mongo-seed
    networks:
      - tracking-network
    depends_on:
      - mongo
    volumes:
      - ./mongo-seed:/mongo-seed

  redis:
    container_name: "redis-pubsub"
    image: "redis:latest"
    networks:
      - tracking-network
    ports:
      - 6379:6379

networks:
  tracking-network:
    driver: bridge
